name: Updater CI

on: workflow_dispatch

jobs:
  release-update:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'zzzgydi')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "yarn"

      - name: Yarn install
        run: yarn install --network-timeout 1000000 --frozen-lockfile

      - name: Release updater file
        run: yarn run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
